orchestrator:
  host: "localhost"
  port: 8080

agents:
  - host: "localhost"
    port: 8081
  - host: "localhost"
    port: 8082

logging:
  level: "info"

timeouts:
  agent_response: 5s  # Таймаут ожидания ответа от агента
